import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync('dist/index.html','utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
for(const [,script] of scripts)new vm.Script(script);
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]);
if(new Set(ids).size!==ids.length)throw Error('Duplicate IDs');
for(const [,target] of html.matchAll(/href="#([^"]+)"/g))if(!ids.includes(target))throw Error('Missing anchor: '+target);
const script=scripts[0][1].split('const canvas=')[0];
const elements=new Map();
function el(id){if(!elements.has(id))elements.set(id,{value:id==='hours'?'20':id==='cost'?'25':id==='business'?'Empresa ejemplo':id==='goal'?'Automatizar mi operación':'',textContent:'',setAttribute(){},addEventListener(type,fn){this[type]=fn},classList:{toggle(){return true},remove(){}},focus(){}});return elements.get(id)}
const tabs=[el('tab0'),el('tab1'),el('tab2')];
const context={document:{getElementById:el,querySelector:s=>el(s),querySelectorAll:s=>s==='[data-flow]'?tabs:[],createElement:()=>({click(){context.downloaded=true}})},Intl,Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},setTimeout:()=>{}};
vm.createContext(context);vm.runInContext(script,context);
if(el('savedHours').textContent!=='56 h')throw Error('ROI hours');
el('hours').value='40';el('hours').input();if(el('savedHours').textContent!=='112 h')throw Error('ROI update');
tabs[1].click();el('simulate').click();if(!el('flowResult').textContent.includes('pedido validado'))throw Error('Flow interaction');
el('brief').submit({preventDefault(){}});if(!context.downloaded)throw Error('Brief download');
console.log('Passed: JavaScript syntax, unique IDs, navigation anchors, ROI updates, flow switching and brief download.');
if(/Nexo|NEXO|>nexo</.test(html))throw Error('Old branding');
if(!html.includes('href="https://wacrm-weld-eight.vercel.app/dashboard"'))throw Error('CRM destination');
const categories=['Atención y ventas','Negocios locales','Operación y datos'];
const cards=[...html.matchAll(/class="product" data-category="([^"]+)"/g)].map(m=>({dataset:{category:m[1]},hidden:false}));
if(cards.length!==17)throw Error('Product catalog');
const buttons=categories.map(category=>({dataset:{categoryFilter:category},setAttribute(){},addEventListener(t,fn){this[t]=fn}}));
const socials=[...html.matchAll(/data-social="([^"]+)"/g)].map(m=>({dataset:{social:m[1]},addEventListener(t,fn){this[t]=fn}}));
if(socials.length!==7)throw Error('Social icons');
const productButtons=[{dataset:{product:'DriveIA'},addEventListener(t,fn){this[t]=fn}}];
el('contacto').scrollIntoView=()=>{};
context.matchMedia=()=>({matches:true});
context.document.querySelectorAll=s=>s==='[data-social]'?socials:s==='[data-category-filter]'?buttons:s==='.product'?cards:s==='[data-product]'?productButtons:[];
vm.runInContext(scripts[1][1],context);
buttons[0].click();if(cards.filter(c=>!c.hidden).length!==5)throw Error('Sales product filtering');
buttons[1].click();if(cards.filter(c=>!c.hidden).length!==9)throw Error('Local businesses filtering');
socials[0].click();if(!el('socialStatus').textContent.includes('perfil demo'))throw Error('Demo social feedback');
productButtons[0].click({preventDefault(){}});if(el('goal').value!=='DriveIA')throw Error('Product brief prefill');
console.log('Passed: Betha branding, CRM destination, product catalog, filters, seven demo social icons and brief prefill.');

const featured=JSON.parse(fs.readFileSync('proyectos-destacados.json','utf8'));
if(featured.length!==17||new Set(featured.map(p=>p.url)).size!==17)throw Error('Featured URLs');
for(const p of featured){if(!html.includes('href="'+p.url+'"'))throw Error('Missing project destination: '+p.name);if(!html.includes('<option>'+p.name+'</option>'))throw Error('Missing brief option: '+p.name)}
console.log('Passed: all 17 supplied project URLs and product brief options.');
